
variables:
  MONO_VERSION: 5_16_0
  XCODE_VERSION: 10.1

jobs:

  - job: build
    displayName: 'Build Libraries & NuGets (macOS)'
    pool:
      vmImage: macos-10.13
    steps:
      # Make sure to select the correct Xamarin and mono
      - bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
        displayName: 'Switch to the latest Xamarin SDK'
      - bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCODE_VERSION).app;sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
        displayName: 'Switch to the latest Xcode'
      # Build
      - script: msbuild /restore vernacular.sln
      - script: nuget install NUnit.ConsoleRunner -ExcludeVersion -OutputDirectory packages
      # Test
      - script: mono packages/NUnit.ConsoleRunner/tools/nunit3-console.exe -trace=verbose Vernacular.Test/bin/Debug/net47/Vernacular.Test.dll
