
variables:
  MONO_VERSION: 5_16_0
  XCODE_VERSION: 10.1
  CONFIGURATION: Release
  PACKAGE_VERSION: 1.1.0

jobs:

  - job: build
    displayName: 'Build (macOS)'
    pool:
      vmImage: macos-10.13
    steps:
      # Make sure to select the correct Xamarin and mono
      - bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
        displayName: 'Switch to the latest Xamarin SDK'
      - bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCODE_VERSION).app;sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
        displayName: 'Switch to the latest Xcode'
      # Build
      - script: msbuild Vernacular.sln /restore /p:Configuration=$(CONFIGURATION)
        displayName: 'Build the projects'
      - script: msbuild /t:pack /p:Configuration=$(CONFIGURATION) /p:PackageOutputPath=../output /p:PackageVersion=$(PACKAGE_VERSION) Vernacular.Catalog.XamarinForms/Vernacular.Catalog.XamarinForms.csproj
        displayName: 'Pack the NuGets'
      # Test
      - script: nuget install NUnit.ConsoleRunner -ExcludeVersion -OutputDirectory packages
        displayName: 'Download the NUnit test runner'
      - script: mono packages/NUnit.ConsoleRunner/tools/nunit3-console.exe -result:output/TestResult.xml Vernacular.Test/bin/$(CONFIGURATION)/net47/Vernacular.Test.dll
        displayName: 'Run the tests'
      # Publish
      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testResultsFormat: NUnit
          testResultsFiles: 'output/TestResult.xml'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifacts'
        inputs:
          pathToPublish: 'output'
          artifactName: 'nuget'
